language: ruby
cache: bundler
rvm:
- 2.6.3
addons:
  apt:
    packages:
    - openjdk-8-jre
before_install:
- gem update --system
- gem install bundler
- nvm install node
install:
- bundle install --jobs=3 --retry=3
- pip install --user html5validator
- npm install -g pa11y-ci
script:
- bundle exec jekyll clean && bundle exec jekyll build
- html5validator --Werror --also-check-css --also-check-svg --root _site/
- |
  (bundle exec jekyll server -d _tmp_site & echo $! >&3) 3>jekyll.pid | grep -q 'Server running' && \
  pa11y-ci --sitemap http://localhost:4000/whiteglass/sitemap.xml && \
  kill -9 "$(cat jekyll.pid)" && \
  rm -f jekyll.pid
branches:
  only:
  - master
deploy:
  provider: pages
  skip_cleanup: true
  keep-history: true
  local-dir: _site
  target-branch: gh-pages
  on:
    branch: master

  env:
    global:
      - secure: "AaQ5EQ7bHT84aGIknHhVBwh7xJ3GJBgZ7KaW1oEvxoDS+xz0gp42/i0AvMZKsZ2uz5eMFuxnWxZDtH16OVoBD91FIVA7eKPeKA8U1xrCLRsWvm2kJ4beo6snaIYiX76HdW3i9gKh+ykuPOFXKZvPf4TqhCcLYSPbns/RzaRgFIpId07xNNfrEveSIMWJp420BM0zIdD5MHAniF7BV6S01TEMtF96i7Krge2Ja9iHVuKpVwuptxHzyBZ2brTAbdh4Uyo791UwC1nfl9LrCB0QSRIpcQNf2z3ZetKFicnilikxjKv1BAC+gqbIRuL/brHioNjpFDCqjvUChIhhptVTA7d+hA4tncXaNOhxYrgHPmow+2hAkEjkxk1aJUzM4FAX8Ka0s92acdphbzWFlXFKQQ1mn6gJFQxkIxegZItcWR4I6SOP2lr+5RgDR/xRyWJDAZOEtQobej8sM3iqEIpEAp2/qLjVFmJhY5k3DxSbezHtiQwjPxV6mi5gdVnaNEsNE53efiIVu7DefY1zPcPAnBD9+Hc/2DGayDAxvbAarUCnUHhOPi0qXc3EAOzPXZPBpRJZhX+5Qa/E/aqJSDNJHPSAwGzc0Jzgr+mqPq1VMVqttKIDxRS9EPSKu9CZkoSmB06xg99/xRS7DKwCuzS/wsyBzDjGZVG4l87+o3HPFA0="
