language: ruby
cache: bundler
rvm:
- 2.6.3
addons:
  apt:
    packages:
    - openjdk-8-jre
before_install:
- gem update --system
- gem install bundler
- nvm install node
install:
- bundle install --jobs=3 --retry=3
- pip install --user html5validator
- npm install -g pa11y-ci
script:
- bundle exec jekyll clean && bundle exec jekyll build
- html5validator --Werror --also-check-css --also-check-svg --root _site/
- |
  (bundle exec jekyll server -d _tmp_site & echo $! >&3) 3>jekyll.pid | grep -q 'Server running' && \
  pa11y-ci --sitemap http://localhost:4000/whiteglass/sitemap.xml && \
  kill -9 "$(cat jekyll.pid)" && \
  rm -f jekyll.pid
branches:
  only:
  - master
deploy:
  provider: pages
  skip_cleanup: true
  github-token: f2wDbB1CETIvQhBSDca0FV8ZKvr13op3lZJy6DybQZ5xk4qsBCucLr0Dz2El/v/z8V3ZCAwKKgLuh6+I6nofpIazRKB9SMSVvPdv6fjd06KW08l3KUy0GjWtmB7aOr4HLzHyiLEqXZXoo9pYGl2QKPxH8kJjj0jxDuBdxy6M5ndYOZlqgUXayFqyg5j4UZ86X+4ZHYc0azesyisiPNJSbaI9lIS8YxVfThJWrxvkHIykiGlcgNippURT7MEOAJBeJlIKW7oDw0R0rPVSB7lUJU2NE8IgcTeTLMm0D00oIfYq1D/V4wr1dxeglgFPV0R8Go81ojye5N2EEIvVecd6T/EeWJrdjlPV5K+f9HfdrmOwMqsHLDG1u5buxvgL6fNjWnU/j+Ml89RyHkJGsCxXcrct4NZy7UdwWl4YLwbkn6mctUvPtKEShndKBu1Dih7GZ1X/C7N65EBsdlpoEhKdxvZE6QWtuIR78MgxfXS1QN9iHFVcAu28TNx/nvrjPKs/AIicIZc0PM/XZL7wVJpb5ZURC78IK0c9JdvcYXw0lQFQZNTvp1Oio65wRSUBVjBZetitnRE0iMsL2SPycuewStthz5LRIBX8PTNk6EhqexH0/lll+1xi43GuYnvpQzgpBCm59A9clTBxaGBHUHvFg3QWWlN0jE2sNVhaFXzq2Z4=
  keep-history: true
  local-dir: _site
  target-branch: gh-pages
  on:
    branch: master
env:
  global:
  - secure: jJJMhVOozqDtcVPtRBPUGrRn1qx9f8G2xVen2sg810ylUNDbuYvHXVh2g96dX7IZdbmLEwWwv0S1XuLeITT2QWtz+/QX3wtncKQt59ZeAlFj3PWl76KAuWju+zwOhVt0JNdKX9r1CKXIKivxuXDjvCyO+k3YnbYrwQ0aD1yUsnxNWiYGmlaaQte+Oa7hQq2kRkAXi5n5ynWVRo2JjUY6nRUbvSyMyKWRgGSCSH/HPLdXNa3kw3Hv2jO/5l4e+bgPZY3iSieg7Aay9o/zEoyw+mAXc4k2fgdRVsbmSLVJ2LXcedrABfqGLY3CmxfhNRlEShdTcbDfYk8gOk5xlS0Tiz9XZT6e4+2JB3Zen9nlJxOoiJTlSH5suEWTovxGbSgAygNs4C1xnA+Hq3WG98zHoKIQqOAVFWJEm7aT5LtVSSGIHeXL9FqCDUhly2k3DI0RYw7WNkvXj4/VL9bTUB4ZfE2Bhszi2V/A6MA8Tepq0kX97nxfgI5++7H4xs4+tkV2rtwDPZUZwj5yFqxOPvLrXHozkxJDA5qLphw0qE4tHDHreloMN0QSEzxEEr6B9SdWjCf5X9ldC7UOWR9CiT/ctw+pnO7l/3t9ABsOwxf+phu1jrgOzQTg9msNL4cRAbTkGJUfNopHv6SospPob1qHkmwpp5I7MnkZqHdt/tAhZTo=
